load("//tensorflow/lite/micro:build_def.bzl", "tflm_cc_library")

tflm_cc_library(
    name = "mnist_inputs",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"]),
    # hdrs = ["sample0_image_data.h"],
    visibility = ["//visibility:public"],
)
